"""SEEDING

Revision ID: 2cf0577e20e5
Revises: a7e27ffb238b
Create Date: 2024-06-30 17:39:07.128102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cf0577e20e5'
down_revision = 'a7e27ffb238b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
