"""message

Revision ID: 9643ec9c34c1
Revises: 2cf0577e20e5
Create Date: 2024-07-03 16:39:17.545369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9643ec9c34c1'
down_revision = '2cf0577e20e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
