"""message

Revision ID: a7e27ffb238b
Revises: c193fd7995f2
Create Date: 2024-06-30 17:35:55.332952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7e27ffb238b'
down_revision = 'c193fd7995f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
